
const ActionConstants = {
    AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
    AUTHENTICATE_USER_ERROR: "AUTHENTICATE_USER_ERROR",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
    SHOW_TABBAR_ADD: "SHOW_TABBAR_ADD",
    HIDE_TABBAR_ADD: "HIDE_TABBAR_ADD",
    TOGGLE_TABBAR_ADD: "TOGGLE_TABBAR_ADD",
};

export default ActionConstants;