
const ActionConstants = {
    AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
    AUTHENTICATE_USER_ERROR: "AUTHENTICATE_USER_ERROR",
    REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
    REGISTER_USER_ERROR: "REGISTER_USER_ERROR"
};

export default ActionConstants;